# Generated by Django 3.1.3 on 2020-11-04 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_doctor_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='main.doctor'),
        ),
        migrations.AlterField(
            model_name='service',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_of_patient', to='main.patient'),
        ),
    ]
