# Generated by Django 3.1.3 on 2020-11-04 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201104_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='treatment_doctor',
        ),
        migrations.AddField(
            model_name='service',
            name='treatment_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_doctor', to='main.doctor'),
        ),
    ]
