# Generated by Django 3.1.3 on 2020-11-04 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201104_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='treatment_doctor',
        ),
    ]
