# Generated by Django 3.1.3 on 2020-11-04 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_service_treatment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='attending_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_doctor', to='main.doctor'),
        ),
    ]
