# Generated by Django 3.1.3 on 2020-11-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201107_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_appointment',
            field=models.DateTimeField(),
        ),
    ]
